"use client";
import {useEffect,useState} from "react";
const neighborhoods=["Yaba","Surulere","Ikeja","Lekki","Lagos Island","Agege","Ikorodu","Victoria Island"];
const choices={gender:["Male","Female","Non-binary"],skin:["Light","Medium","Brown","Deep"],hair:["Low cut","Waves","Braids","Locs","Afro","Fade"],style:["Street","Casual","Luxury","Corporate","Sport"],background:["Student","Hustler","Professional","Creative","Entrepreneur"]};
export default function Auth(){
 const[u,setU]=useState<any>(null);const[step,setStep]=useState(1);const[mode,setMode]=useState("signup");const[m,setM]=useState("");const[f,setF]=useState<any>({email:"",password:"",name:"",age:"",firstName:"",lastName:"",gender:"",skin:"",hair:"",style:"",background:"",neighborhood:""});
 useEffect(()=>{const x=localStorage.getItem("eko-user");if(x)setU(JSON.parse(x))},[]);
 const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));
 const save=()=>{if(!f.firstName||!f.lastName||!f.gender||!f.skin||!f.hair||!f.style||!f.background||!f.neighborhood)return setM("Complete every character choice.");const x={name:f.name,email:f.email,age:Number(f.age),character:{firstName:f.firstName,lastName:f.lastName,gender:f.gender,skin:f.skin,hair:f.hair,style:f.style,background:f.background,neighborhood:f.neighborhood}};localStorage.setItem("eko-user",JSON.stringify(x));setU(x)};
 if(u)return <main className="auth"><section><h1>Welcome to Eko.</h1><p>{u.character.firstName} {u.character.lastName} • {u.character.neighborhood}</p><button onClick={()=>location.href="/game"}>Enter Eko</button><button onClick={()=>{localStorage.removeItem("eko-user");setU(null)}}>Sign out</button></section></main>;
 if(mode==="login")return <main className="auth"><section><h1>Welcome back.</h1><input placeholder="Email" value={f.email} onChange={e=>set("email",e.target.value)}/><input type="password" placeholder="Password" value={f.password} onChange={e=>set("password",e.target.value)}/><button onClick={()=>{const x=localStorage.getItem("eko-user");if(x&&JSON.parse(x).email===f.email){setU(JSON.parse(x))}else setM("No matching account found.")}}>Sign in</button><button onClick={()=>setMode("signup")}>Create account</button>{m&&<p>{m}</p>}</section></main>;
 return <main className="auth"><section><h1>{step===1?"Create your citizen.":"Build your character."}</h1>{step===1?<><input placeholder="Username" value={f.name} onChange={e=>set("name",e.target.value)}/><input placeholder="Email" value={f.email} onChange={e=>set("email",e.target.value)}/><input type="password" placeholder="Password (8+ characters)" value={f.password} onChange={e=>set("password",e.target.value)}/><input type="number" min="18" placeholder="Age 18+" value={f.age} onChange={e=>set("age",e.target.value)}/><button onClick={()=>{if(!f.name||!f.email||f.password.length<8||Number(f.age)<18)return setM("Enter valid account details and confirm 18+.");setStep(2);setM("")}}>Continue</button><button onClick={()=>setMode("login")}>Already have an account?</button></>:<><div className="two"><input placeholder="First name" value={f.firstName} onChange={e=>set("firstName",e.target.value)}/><input placeholder="Last name" value={f.lastName} onChange={e=>set("lastName",e.target.value)}/></div>{Object.entries(choices).map(([k,opts]:any)=><label key={k}>{k}<select value={f[k]} onChange={e=>set(k,e.target.value)}><option value="">Choose</option>{opts.map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label>neighborhood<select value={f.neighborhood} onChange={e=>set("neighborhood",e.target.value)}><option value="">Choose</option>{neighborhoods.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={save}>Create character</button></>}{m&&<p>{m}</p>}</section></main>}
