"use client";
import {useEffect,useState} from "react";
type Player={name:string;cash:number;bank:number;energy:number;xp:number;wanted:number;job:string;degree:number;vehicle:string;property:string;business:string};
const base:Player={name:"New Citizen",cash:50000,bank:150000,energy:100,xp:0,wanted:0,job:"Unemployed",degree:0,vehicle:"None",property:"Starter apartment",business:"None"};
const jobs:[string,number,number][]=[["Dispatch Rider",25000,18],["Software Intern",45000,15],["Retail Manager",70000,22],["Creative Freelancer",85000,20],["Fintech Analyst",120000,25]];
const cars:[string,number][]=[["Toyota Corolla",900000],["Honda Civic",1400000],["Mercedes C-Class",5200000],["Range Rover Sport",18500000]];
const homes:[string,number][]=[["Yaba Studio",1800000],["Surulere Flat",4500000],["Lekki Apartment",12000000],["VI Penthouse",45000000]];
const businesses:[string,number][]=[["Mini Mart",2500000],["Car Wash",5500000],["Fashion Label",9000000],["Night Lounge",18000000]];
const money=(n:number)=>"₦"+n.toLocaleString();
export default function Game(){
 const[p,setP]=useState(base);const[screen,setScreen]=useState("city");const[log,setLog]=useState<string[]>([]);
 useEffect(()=>{const x=localStorage.getItem("eko-game");if(x)setP(JSON.parse(x))},[]);
 useEffect(()=>localStorage.setItem("eko-game",JSON.stringify(p)),[p]);
 const say=(s:string)=>setLog(x=>[s,...x].slice(0,6));
 const earn=(n:number,s:string)=>{setP(x=>({...x,cash:x.cash+n,xp:x.xp+Math.max(5,Math.floor(n/5000)),energy:Math.max(0,x.energy-8)}));say("+"+money(n)+" • "+s)};
 const spend=(n:number,s:string)=>{if(p.cash<n){say("Not enough cash");return false}setP(x=>({...x,cash:x.cash-n,xp:x.xp+3}));say("-"+money(n)+" • "+s);return true};
 const work=(j:any)=>{if(p.energy<j[2])return say("Too tired. Rest first.");setP(x=>({...x,job:j[0],energy:x.energy-j[2]}));earn(j[1],j[0]+" shift")};
 const nav=[["city","City"],["jobs","Jobs"],["bank","Bank"],["university","University"],["garage","Garage"],["property","Property"],["business","Business"],["police","Police"]];
 return <main className="game"><style>{`
.game{min-height:100vh;background:#080a08;color:#f5f5ef;font-family:Arial,sans-serif;padding:24px}.game *{box-sizing:border-box}.bar{max-width:1200px;margin:auto;display:flex;gap:10px;align-items:center;justify-content:space-between;border-bottom:1px solid #ffffff12;padding-bottom:18px}.logo{font-size:28px;font-weight:900}.logo span{color:#b8d83d}.nav{display:flex;gap:6px;flex-wrap:wrap}.nav button,.btn{border:1px solid #ffffff12;background:#111510;color:#ddd;border-radius:9px;padding:10px 13px}.nav .sel,.btn.primary{background:#b8d83d;color:#10130d;font-weight:800}.stats{display:flex;gap:8px;flex-wrap:wrap}.stats b{background:#111510;border:1px solid #ffffff10;border-radius:999px;padding:9px 12px;font-size:12px}.wrap{max-width:1200px;margin:30px auto}.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.hero>div,.panel{background:#101410;border:1px solid #ffffff10;border-radius:22px;padding:25px}.hero h1{font-size:clamp(42px,6vw,78px);line-height:.9;letter-spacing:-4px;margin:18px 0}.hero em{color:#b8d83d;font-style:normal}.muted,small{color:#858b83}.map{min-height:380px;position:relative;overflow:hidden;background:linear-gradient(140deg,#172019,#0d110d)}.road{position:absolute;background:#ffffff0b}.r1{height:45px;width:130%;top:44%;left:-15%;transform:rotate(-12deg)}.r2{height:130%;width:45px;left:55%;top:-15%;transform:rotate(15deg)}.place{position:absolute;border:1px solid #ffffff22;background:#101410;color:#eee;border-radius:999px;padding:7px 10px;font-size:11px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}.panel h2{margin:0 0 6px}.row{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:14px;background:#151915;border-radius:12px;margin:8px 0}.row small{display:block;margin-top:5px}.balance{display:grid;grid-template-columns:1fr 1fr;gap:10px}.balance div{background:#171c17;padding:18px;border-radius:14px}.balance strong{display:block;font-size:23px;margin-top:6px}.input{width:100%;background:#080a08;color:#fff;border:1px solid #ffffff18;padding:13px;border-radius:10px;margin:15px 0}.progress{height:10px;background:#252b24;border-radius:99px;overflow:hidden}.progress span{display:block;height:100%;background:#b8d83d}.tiles{display:grid;grid-template-columns:1fr 1fr;gap:12px}.tile{background:#151915;border:1px solid #ffffff0b;border-radius:14px;padding:18px;text-align:left;color:#fff}.log{position:fixed;right:20px;bottom:20px;background:#b8d83d;color:#10130d;border-radius:12px;padding:12px 15px;font-weight:800;max-width:320px}.danger{color:#ff9b7a}@media(max-width:850px){.game{padding:14px}.hero{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.bar{align-items:flex-start;flex-direction:column}.stats{width:100%}}@media(max-width:600px){.tiles,.balance{grid-template-columns:1fr}.hero h1{letter-spacing:-2px}}`}</style>
<div className="bar"><div className="logo">EKO<span>•</span></div><div className="nav">{nav.map(n=><button className={screen===n[0]?"sel":""} key={n[0]} onClick={()=>setScreen(n[0])}>{n[1]}</button>)}</div><div className="stats"><b>{money(p.cash)} cash</b><b>{money(p.bank)} bank</b><b>⚡ {p.energy}%</b><b>LV {Math.floor(p.xp/100)+1}</b></div></div>
<div className="wrap">{screen==="city"&&<><div className="hero"><div><small>LAGOS / LIVE WORLD</small><h1>Live the city.<br/><em>Own the lifestyle.</em></h1><p className="muted">Your character can work, study, buy vehicles, own property, run businesses and deal with the consequences of a living Lagos economy.</p><button className="btn primary" onClick={()=>earn(12000,"Quick city gig")}>Quick gig +₦12k</button></div><div className="map"><div className="road r1"/><div className="road r2"/>{["Yaba","Lekki","Ikeja","Surulere","Victoria Island","Agege","Ikorodu","Lagos Island"].map((x,i)=><button className="place" style={{left:(10+i*11)+"%",top:(20+(i*19)%65)+"%"}} key={x}>{x}</button>)}</div></div><div className="grid"><div className="panel"><small>JOB</small><h2>{p.job}</h2><p className="muted">Work shifts to build cash and XP.</p></div><div className="panel"><small>DEGREE</small><h2>{p.degree}%</h2><div className="progress"><span style={{width:p.degree+"%"}}/></div></div><div className="panel"><small>POLICE</small><h2 className={p.wanted?"danger":""}>{p.wanted}/5 wanted</h2><p className="muted">Heat affects your legal status.</p></div></div></>}
{screen==="jobs"&&<Panel title="Jobs" sub="Choose a career and work shifts."><div>{jobs.map(j=><div className="row" key={j[0]}><div><b>{j[0]}</b><small>{money(j[1])} • {j[2]} energy</small></div><button className="btn primary" onClick={()=>work(j)}>Work</button></div>)}</div><button className="btn" onClick={()=>setP(x=>({...x,energy:Math.min(100,x.energy+35)}))}>Rest +35 energy</button></Panel>}
{screen==="bank"&&<Bank p={p} setP={setP} say={say}/>}
{screen==="university"&&<Panel title="Eko University" sub={p.degree+"% course progress"}><div className="progress"><span style={{width:p.degree+"%"}}/></div><div className="tiles">{["Attend class","Study","Campus event","Internship"].map((x,i)=><button className="tile" key={x} onClick={()=>{if(p.energy<10)return say("Not enough energy");setP(v=>({...v,degree:Math.min(100,v.degree+(i===1?15:8)),energy:v.energy-10,xp:v.xp+10}));say(x+" completed")}}><b>{x}</b><small> +{i===1?15:8}%</small></button>)}</div>{p.degree>=100&&<button className="btn primary" onClick={()=>{setP(x=>({...x,degree:0}));earn(150000,"Semester completed")}}>Complete semester +₦150k</button>}</Panel>}
{screen==="garage"&&<Shop title="Garage"current={p.vehicle}items={cars}spend={spend}setP={setP}field="vehicle"/>}
{screen==="property"&&<Shop title="Property"current={p.property}items={homes}spend={spend}setP={setP}field="property"/>}
{screen==="business"&&<Shop title="Businesses"current={p.business}items={businesses}spend={spend}setP={setP}field="business" revenue/>}
{screen==="police"&&<Panel title="Police & legal" sub="Wanted level and fictional risk system."><div className="panel"><h2 className={p.wanted?"danger":""}>Wanted {p.wanted}/5</h2><div style={{fontSize:26}}>{"★".repeat(p.wanted)}{"☆".repeat(5-p.wanted)}</div></div><div className="tiles"><button className="tile" onClick={()=>{setP(x=>({...x,wanted:Math.max(0,x.wanted-1)}));say("Heat reduced")}}>Lay low<br/><small>Reduce heat</small></button><button className="tile" onClick={()=>{setP(x=>({...x,wanted:Math.min(5,x.wanted+1)}));say("Risky fictional mission started")}}>Risky mission<br/><small>Increase heat</small></button></div></Panel>}</div>{log[0]&&<div className="log">{log[0]}</div>}</main>}
function Panel({title,sub,children}:any){return <section className="panel"><h2>{title}</h2><p className="muted">{sub}</p>{children}</section>}
function Bank({p,setP,say}:any){const[a,setA]=useState("");const n=Number(a)||0;return <Panel title="EkoBank" sub="Manage your money."><div className="balance"><div><small>Cash</small><strong>{money(p.cash)}</strong></div><div><small>Bank</small><strong>{money(p.bank)}</strong></div></div><input className="input" placeholder="Amount" value={a} onChange={e=>setA(e.target.value)}/><button className="btn primary" onClick={()=>{if(n>0&&n<=p.cash){setP((x:Player)=>({...x,cash:x.cash-n,bank:x.bank+n}));say("Deposit complete")}else say("Invalid amount")}}>Deposit</button> <button className="btn" onClick={()=>{if(n>0&&n<=p.bank){setP((x:Player)=>({...x,cash:x.cash+n,bank:x.bank-n}));say("Withdrawal complete")}else say("Invalid amount")}}>Withdraw</button></Panel>}
function Shop({title,current,items,spend,setP,field,revenue}:any){return <Panel title={title} sub={"Owned: "+current}><div>{items.map((x:any)=><div className="row" key={x[0]}><div><b>{x[0]}</b><small>{money(x[1])}</small></div><button className="btn primary" onClick={()=>{if(spend(x[1],x[0]+" purchase"))setP((v:Player)=>({...v,[field]:x[0]}))}}>Buy</button></div>)}</div>{revenue&&current!=="None"&&<button className="btn primary" onClick={()=>{setP((x:Player)=>({...x,cash:x.cash+75000}));}}>Collect +₦75k revenue</button>}</Panel>}
